title: "@relaycorp/awala-keystore-cloud"

markdown: kramdown

baseurl: /awala-keystore-cloud-js
remote_theme: just-the-docs/just-the-docs@v0.3.3

footer_content: "Copyright &copy; 2022 Relaycorp, Inc."

aux_links:
  "GitHub project":
    - "https://github.com/relaycorp/awala-keystore-cloud-js"

search_enabled: false
